### ISSUE TITLE
app wont launch

### ISSUE THREAD

**Issue by gnoe454** [tronikos/FlumeSmartThings#1]
once i enter my information in the options section and select done i get the processing window and it goes back to my list of apps. Selecting the app again puts me back in the options section with a blank PW field. It still includes the the statement to include the API information in IDE statement. any idea what might be wrong?

I've seen comments about app only working on the classic app, I'm using the new app is that my issue?

**Comment by tronikos** [comment]
Only the new app is supported so you are good there.
Are you using the proxy? If not, installation might fail due to throttling.
I recommend checking Live Logging, e.g. https://graph-na04-useast2.api.smartthings.com/ide/logs (your URL might be different depending on your location) for any errors.

**Comment by gnoe454** [comment]
Thanks for your reply. My question is do I need the app at all? The device
is able to determine whether the Flume sensor is "wet"  or not and I can
turn off my water valve so I achieved my goal but I still can't open the
app, it's all in the device. Is that how it's supposed to work?

**Comment by tronikos** [comment]
Yes that's how it's supposed to work. You need the app for the device to properly function but you don't need to open the app settings unless you want to reconfigure something.

**Comment by gnoe454** [comment]
Ok, thanks for the clarification.
